### ISSUE TITLE
Refactor RIMS sensor layout

### ISSUE THREAD

**Issue by kyleoliveira** [Ohmbrewer/rhizome#25]
After thinking about it a bit, we've come to the conclusion that the sensor layout in the RIMS configuration doesn't make much sense with respect to how we want to run our PID algorithm. Namely, the PID algorithm should be contained within the Thermostat and in order for it to work properly, it needs to know the temperature of the mash - not the temperature in the tube. Hence,

1) Fix the names of getters/setters within RIMS so that the TemperatureSensor that will track temperature in the tun is the one within the RIMS object's Thermostat.
2) Fix the names of getters/setters within RIMS so that the TemperatureSensor that will track temperature in the tube is the non-Thermostat sensor for the RIMS. Name it something like "safety sensor" or "check sensor" as it is intended to provide the RIMS with a warning for when the tube is reaching unacceptable heating limits.
3) Provide delegating getters/setters within RIMS for both sensors for ease of use in display functions and so forth.
4) Double-check that you've fixed up display methods, update methods, and constructors so that things are "wired" correctly.

**Comment by azyth** [comment]
Been thinking about this, and it may be pretty simple, mainly thermostat will want a "safety sensor".  we can keep most things the same and just add a few getter/setter type things in thermostat.

and switching which sensor is set as the Therm temp sensor (needs to be mash sensor, not tube sensor)

**Comment by kyleoliveira** [comment]
That seems reasonable to me. Go for it.
