### ISSUE TITLE
Make ID's transparent to the User

### ISSUE THREAD

**Issue by kyleoliveira** [Ohmbrewer/rhizome#32]
@Ohmbrewer/web-team 
So far we've been manually setting the IDs and we've implemented a few solutions for subsystems in Thermostat and RIMS. However, it would make it a lot easier for the Ohmbrewer app to talk to the Rhizome if we made it more transparent. Specifically, I would like to remove the Equipment ID from all constructors and set it according to a unique property of the Equipment in question. For most of the Equipment, this would be a pin number. For the Onewire sensors, we'd have to get a little creative. I'm thinking:
- Relay, Pump & Heating Element: power pin
- Thermostat: Element power pin
- RIMS: Thermostat's ID
- Temperature Sensor: Bus index?

Thoughts? I feel like this will make communications much easier to automate.

**Comment by azyth** [comment]
I think this is a good idea in general but there will be some snags. 

all relays are inherently flexible as to which pin they use. so that might get iffy

in theory if one was unused you could just use the other since it would have to be unique since we only have one of each pin, but that is less specific and might get confusing.

**Comment by kyleoliveira** [comment]
From a programming perspective, though aren't we requiring that, at least, the "power" pin be set for all Relay-based Equipment? I thought we're using the "control" pin for a particular purpose (modulation) and it wouldn't be appropriate to swap them. 
I mean, it might not matter physically, but we do want to make the distinction in what the Rhizome will be doing with a particular pin, right?

**Comment by azyth** [comment]
nope, relays have the control pin set by default, but the power pin may or may not be set, and pumps (currently) only set the power pin.

**Comment by kyleoliveira** [comment]
We talked it over via Hangouts and it seems like these are the pins that we could require always be used:
- Relay & Pump: Power Pin 
- Heating Element: Control Pin
- Thermostat: Element ID
- RIMS: Thermostat's ID

Still not 100% on the Temperature Sensor, though. I'd like to try Bus index and see how that goes because it seems like it would be fairly straight-forward to get the Probe info screen to display in that order (if it isn't already) and then the user wouldn't have to keep track of the OneWire address.

Sound good?

**Comment by azyth** [comment]
bus index changes every time it queries. so I think the best way would be to keep track internally of the HEx addresses and somehow just convert them to an equivalent int or something for display to the user. This will involve some creative code i think.

**Comment by kyleoliveira** [comment]
Damn, I was hoping that as long as you didn't change the wiring they'd always return in the same order.

So, for now let's stick with identifying the sensor via the (hex) Bus Address. #49 should provide a way to at least display that to the user, which would allow us to make the association in the web app. With respect to the ID that gets displayed, I think I'll have to think about it a bit. 
We do have the Sprouts class now, so we could conceivably just track a "last sensor ID" and always assign a new sensor to that ID+1, but I don't know how well that will work within Thermostat and RIMS given that we're currently auto-assigning those numbers. Maybe we could combine the two ideas?: set the sensor ID to always == the Thermostat ID, and any sensor that isn't associated with a Thermostat is set to the next value in the sequence (sequence starts at 6 since we can have 6 Thermostats max*).

Let me know if you come up with something, though.
- Assuming we set up each Thermostat with a HE on a single SSR/DPDT.

**Comment by kyleoliveira** [comment]
This closed itself automagically. Reopening since it's not done.

**Comment by kyleoliveira** [comment]
We've confirmed that OneWire probes _do_ indeed return in the same order every time. So we _can_ use that as an identifier. Here's where we stand now:

| Type | Automatic Identifier |
| --- | --- |
| Temperature Sensor (OneWire) | Index on the bus |
| Relay | Power pin |
| Pump | Power pin |
| Heating Element | Control pin |
| Thermostat | Element ID |
| RIMS | Thermostat's ID |

Any objections?

**Comment by azyth** [comment]
should make relay control pin as well.

**Comment by kyleoliveira** [comment]
Moving this to the next Sprint since we don't even have a PR for this yet.

**Comment by kyleoliveira** [comment]
Talked it over with John and here's the final thing we came up with:

| Type | Automatic Identifier |
| --- | --- |
| Temperature Sensor (OneWire) | Index on the bus |
| Relay | Control pin |
| Pump | Control pin |
| Heating Element | Control pin |
| Thermostat | Element ID |
| RIMS | Thermostat's ID |

This will necessitate a small refactoring w.r.t. Relay/Pump and how they set pins, so I'm putting this on hold until #70 is done.
