### ISSUE TITLE
TemperatureSensor constructors should take a Probe object (not pins)

### ISSUE THREAD

**Issue by kyleoliveira** [Ohmbrewer/rhizome#34]
We designed the TemperatureSensor so that it has an internal Probe object that takes care of any technical concerns revolving around reading the sensor such as whether you need one or more pins or how the hardware is identified (by pin or by bus ID). However, the TemperatureSensor constructors are currently set up to take a bus pin setting and are all hardwired to use the Onewire probe.

We should refactor all of the TemperatureSensor constructors so they take a pointer to an appropriately initialized Probe object instead of any sort of pin setup info. For example, this:

``` c++
// signature
TemperatureSensor(int id, int busPin);

// used like
ts = TemperatureSensor(1, D0);
```

should change to this

``` c++
// signature
TemperatureSensor(int id, Probe probe);

// used like
ts = TemperatureSensor(1, new Onewire());
```

Thoughts?

**Comment by azyth** [comment]
do we want this chain to cascade all the way back up to the top ?  -> Thermostat -> RIMS -> ... or just keep it relegated to the temperature sensor level.  
I am of two opinions on this, 
1. it would be nice to be able to control the probe object from constructors
2. it is going to be rather clunky to build and pass all this via constructors, and might be better to use getter/setter to change probes if we are trying to alter equipment .  (thinking of changing probe type in the UI menu)

**Comment by kyleoliveira** [comment]
I'd say for now it's safe to keep it at the Temperature Sensor level and just have the Thermostat always use a Onewire probe. When we get to the point where we want to support other probe types, it won't be very difficult to add that support - it may be as simple as adding a constructor with a "mode" flag to the Thermostat and RIMS classes.
