### ISSUE TITLE
Make sure Rhizome is publishing status changes

### ISSUE THREAD

**Issue by kyleoliveira** [Ohmbrewer/rhizome#37]
Ohmbrewer's web app is going to rely on updates about status, so we need to be sure that when stuff changes in (at least) the Heating Elements, Temperature Sensors, and Pumps a status message is published.

Coordinate with @kyleoliveira on the expected interface.

**Comment by kyleoliveira** [comment]
@Ohmbrewer/web-team  Here are the times I would expect an update to be sent out:

| When | Class | What to send |
| --- | --- | --- |
| Every 15 seconds | TemperatureSensor | Current Sensor reading |
| When Stop Time is reached (and the Equipment shuts off) | Everybody | Equipment state (maybe) |
| ~~When State changes~~ | ~~Relay/Pump/Thermostat~~ | ~~Current state~~ |
| When Target Temperature reached | Thermostat | ??? (Probably a simple notification on the channel, since we're already getting regular sensor updates) |
| When Max Temperature is reached and cooldown starts | RIMS | ??? (Mostly just needs to go to the right event channel) |
| When cooldown ends | RIMS | ??? (Mostly just needs to go to the right event channel) |

For all of these I'd want to include the Equipment ID and the Current Task. 

I don't think we need notifications about State change for RIMS since its subsystems will probably be sending that information out. I'm on the fence as to whether we want a notification about state change (other than Stop Time shutoff) from HeatingElement since we'll be modulating it so much with the Thermostat. I don't think it would hurt aside from taking up processing time, but I don't know if we gain enough to make it worthwhile either.

What do you think? Did I miss anything?

**Comment by azyth** [comment]
as for state change it is possible that it can be updated and changed very rapidly in a short period of time. so i think omitting the low levels is fine.

**Comment by kyleoliveira** [comment]
Now that you mention it, I think you're right about the state, but for a different reason. The only one that's going to toggle state rapidly is the Heating Element (I mean you could do the same thing with Relay, but we don't support that currently).

Instead, I think we can leave it out because 1) we get an ACK when sending an update that toggles state telling us if the update was successful and 2) we should be getting a notification if the state changes due to stop time. The only other situations where state would change are a) a supersystem (Thermostat, RIMS) toggled it or b) something outside of our control happened (loss of power?). I think you're thinking of (a) and I agree we don't want that many updates. As for (b), that's more of a system-wide issue that we'll want to figure out a procedure for. So, yeah, I think it's safe to assume the state will remain the same barring (a) and (b) and we can scratch sending updates on state change.

**Comment by kyleoliveira** [comment]
Added an extra requirement for #52 that should handle the Stop Time -related update. All other requirements should be met, so I'm going to close this off.
