### ISSUE TITLE
Rhizome testing

### ISSUE THREAD

**Issue by azyth** [Ohmbrewer/rhizome#48]
@Ohmbrewer/hops-team Post issues that deserve to be looked at for rhizome beta version release here: 

display multiple therms is buggy (may be fixed by dynamic add PR)
powerpin not shutting off once target temp is reached, ?

**Comment by kyleoliveira** [comment]
#30 should have handled the multiple Thermostats issue. Not sure if you want to log a separate Issue for the other bug...

**Comment by azyth** [comment]
power pin issue appears to be ok now as well
