### ISSUE TITLE
Build out basic menu feature

### ISSUE THREAD

**Issue by azyth** [Ohmbrewer/rhizome#71]
implement the basic interactive menu for the display, 
- button press functionality
- basic menu
- navigation of menu

**Comment by azyth** [comment]
@nischalvasant How is the pull request coming for this?

**Comment by chillinginchaos** [comment]
I'm working on a state diagram for the menu... I'm trying to figure out the best way to keep track of "where I am" in the menu, and also how to go "back" to the screen I was on before I entered the menu.

**Comment by kyleoliveira** [comment]
Resolved by #73 , though we need another issue for calibration. We should open additional issues for other screens/menus as needed.
